version: "3.9"
services:
  scratchpad:
    tty: true
    build: .
    ports:
      - "3000:3000"
      - "6006:6006"
    volumes:
      - type: bind
        source: ./src
        target: /home/node/app/src
      - type: bind
        source: ./.env
        target: /home/node/app/.env
  redis:
    image: "redis:alpine"
